<Project>
	<PropertyGroup>
		<_IsOnBrowser>false</_IsOnBrowser>
		<_IsOnBrowser Condition="(!$(TargetFrameworks.Contains('-browser')) And $(BuildToBrowser) == 'true') Or $([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'browser'">true</_IsOnBrowser>
		<_CiderTest>false</_CiderTest>
		<_CiderTest Condition="$(CiderTest) == 'true'">true</_CiderTest>
	</PropertyGroup>
	<Import Condition="!$(_IsOnBrowser)" Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />
	<Import Condition="$(_IsOnBrowser)" Project="Sdk.props" Sdk="Microsoft.NET.Sdk.WebAssembly" />

	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == '' And !$(_IsOnBrowser)">
		<OutputType>WinExe</OutputType>
	</PropertyGroup>

	<ItemGroup Condition="$(_CiderTest)">
		<ProjectReference Include="$(MSBuildThisFileDirectory)..\..\Cider\Cider.csproj" />
		<ProjectReference Include="$(MSBuildThisFileDirectory)..\..\Cider.Generator\Cider.Generator.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup Condition="!$(_CiderTest)">
		<PackageReference Include="Cider" Version="$(CiderVersion)" />
		<PackageReference Include="Cider.Generator" Version="$(CiderVersion)" />
	</ItemGroup>

	<ItemGroup>
		<CiderAssets Include="$(CiderAssetsPath)\**\*" />

		<_CiderAssetsWithoutMeta Include="@(CiderAssets)" />
		<_CiderAssetsWithoutMeta Remove="**\*.meta" />

		<Content Include="@(_CiderAssetsWithoutMeta)">
			<!--Browser Assets由StaticWebAssetsSdk处理-->
			<CopyToOutputDirectory Condition="!$(_IsOnBrowser)">PreserveNewest</CopyToOutputDirectory>
		</Content>
		
		<CompilerVisibleProperty Include="MSBuildProjectDirectory" />

		<AdditionalFiles Include="**\*.cider" />
		<AdditionalFiles Include="$(CiderAssetsPath)\**\*.meta" />

		<Compile Remove="Platform\**\*.cs" />
	</ItemGroup>

	<!--Android Start-->
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
		<MonoAndroidResourcePrefix Condition="$(MonoAndroidResourcePrefix) == ''">Platform\Android\Resources</MonoAndroidResourcePrefix>
		<AndroidManifest Condition="$(AndroidManifest) == ''">Platform\Android\AndroidManifest.xml</AndroidManifest>
	</PropertyGroup>
	
	<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
		<Compile Include="Platform\Android\**\*.cs" />
		
		<AndroidAsset Include="@(_CiderAssetsWithoutMeta)" />
		<AndroidAsset Remove="**\*.meta" />
		<AndroidAsset Remove="**\*.cider" />
	</ItemGroup>
	<!--Android End-->
	
	<!--Browser Start-->
	<PropertyGroup Condition="$(_IsOnBrowser)">
		<DefineConstants>$(DefineConstants);BROWSER</DefineConstants>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
		<WasmEnableExceptionHandling>false</WasmEnableExceptionHandling>
		<ResolveStaticWebAssetsInputsDependsOn>$(ResolveStaticWebAssetsInputsDependsOn);AddExtraStaticWebAssets</ResolveStaticWebAssetsInputsDependsOn>
		<ExtraStaticAssetsRoot>$(MSBuildProjectDirectory)\$(CiderAssetsPath)\</ExtraStaticAssetsRoot>
	</PropertyGroup>
	
	<ItemGroup Condition="$(_IsOnBrowser)">
		<PackageReference Include="Cider.NativeAssets.WebAssembly" Version="$(CiderVersion)" />
		
		<Compile Include="Platform\Browser\**\*.cs" />
		
		<StaticWebAssetFingerprintPattern Include="JS" Pattern="*.js" Expression="#[.{fingerprint}]!" />
		<!--<NativeFileReference Include="*.a" />-->
		<!--<WasmFilesToIncludeInFileSystem Include="" />-->

		<!--Used by SDL_CreateWindowWithProperties-->
		<EmccExportedRuntimeMethod Include="requestFullscreen" />
	</ItemGroup>

	<Target Name="AddExtraStaticWebAssets" Condition="$(_IsOnBrowser)">
		<DefineStaticWebAssets
			CandidateAssets="@(_CiderAssetsWithoutMeta)"
			SourceId="$(PackageId)"
			SourceType="Discovered"
			AssetKind="All"
			AssetMode="All"
			AssetRole="Primary"
			ContentRoot="$(ExtraStaticAssetsRoot)"
			BasePath="$(StaticWebAssetBasePath)">
			<Output TaskParameter="Assets" ItemName="_ExtraStaticWebAsset" />
		</DefineStaticWebAssets>

		<DefineStaticWebAssetEndpoints
			  CandidateAssets="@(_ExtraStaticWebAsset)"
			  ContentTypeMappings="@(StaticWebAssetContentTypeMapping)"
			  ExistingEndpoints="">
			<Output TaskParameter="Endpoints" ItemName="_ExtraStaticWebAssetEndpoint" />
		</DefineStaticWebAssetEndpoints>

		<ItemGroup>
			<StaticWebAsset Include="@(_ExtraStaticWebAsset)" />
			<StaticWebAssetEndpoint Include="@(_ExtraStaticWebAssetEndpoint)" />
		</ItemGroup>
	</Target>
	<!--Browser End-->
	
	<UsingTask Condition="$(_CiderTest)" TaskName="AssetTask" AssemblyFile="$(MSBuildThisFileDirectory)..\..\Cider.Task\bin\$(Configuration)\netstandard2.0\Cider.Task.dll" />
	<UsingTask Condition="!$(_CiderTest)" TaskName="AssetTask" AssemblyFile="$(MSBuildThisFileDirectory)..\tasks\Cider.Task.dll" />

	<Target Name="CheckConfiguration" BeforeTargets="BeforeBuild">
		<Warning Condition="$(TargetFrameworks.Contains('-browser')) And $(BuildToBrowser) != ''"
			Text="The property BuildToBrowser will be ignored when browser is in TargetFrameworks." />
	</Target>

	<Target Name="AssetMetaPreprocess" BeforeTargets="BeforeBuild">
		<AssetTask Assets="@(CiderAssets)" />
	</Target>

	<Import Condition="!$(_IsOnBrowser)" Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />
	<Import Condition="$(_IsOnBrowser)" Project="Sdk.targets" Sdk="Microsoft.NET.Sdk.WebAssembly" />
</Project>