using Cider.Extensions;
using SDL;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics.CodeAnalysis;

namespace Cider.Input
{
    public static class Keyboard
    {
        public static bool IsKeyboardAvailable => SDL3.SDL_HasKeyboard();

        public static KeyboardState GetState()
        {
            int num;
            unsafe
            {
                var ptr = SDL3.SDL_GetKeyboardState(&num);
                return new(new(ptr, num));
            }
        }

#nullable enable
        public static unsafe bool TryGetFocusedWindow([NotNullWhen(true)] out Window? window)
        {
            return SDL3.SDL_GetWindowID(SDL3.SDL_GetKeyboardFocus()).TryGetWindow(out window);
        }
    }

    public readonly ref struct KeyboardState
    {
        private readonly Span<SDLBool> states;

        internal KeyboardState(Span<SDLBool> states)
        {
            this.states = states;
        }

        public readonly bool this[KeyCode key] => states[(int)key];

        public bool IsDown(KeyCode key) => states[(int)key];
    }

    public static class KeyExtensions
    {
        public static KeySymbol ToSymbol(this KeyCode keyCode) => (KeySymbol)((uint)keyCode | SDL3.SDLK_SCANCODE_MASK);

        public static bool IsFromKeyCode(this KeySymbol keySymbol) => ((uint)keySymbol & SDL3.SDLK_SCANCODE_MASK) != 0;

        public static bool IsExtended(this KeySymbol keySymbol) => ((uint)keySymbol & SDL3.SDLK_EXTENDED_MASK) != 0;
    }

    public enum KeyCode
    {
        Unknown = SDL_Scancode.SDL_SCANCODE_UNKNOWN,

        A = SDL_Scancode.SDL_SCANCODE_A,
        B = SDL_Scancode.SDL_SCANCODE_B,
        C = SDL_Scancode.SDL_SCANCODE_C,
        D = SDL_Scancode.SDL_SCANCODE_D,
        E = SDL_Scancode.SDL_SCANCODE_E,
        F = SDL_Scancode.SDL_SCANCODE_F,
        G = SDL_Scancode.SDL_SCANCODE_G,
        H = SDL_Scancode.SDL_SCANCODE_H,
        I = SDL_Scancode.SDL_SCANCODE_I,
        J = SDL_Scancode.SDL_SCANCODE_J,
        K = SDL_Scancode.SDL_SCANCODE_K,
        L = SDL_Scancode.SDL_SCANCODE_L,
        M = SDL_Scancode.SDL_SCANCODE_M,
        N = SDL_Scancode.SDL_SCANCODE_N,
        O = SDL_Scancode.SDL_SCANCODE_O,
        P = SDL_Scancode.SDL_SCANCODE_P,
        Q = SDL_Scancode.SDL_SCANCODE_Q,
        R = SDL_Scancode.SDL_SCANCODE_R,
        S = SDL_Scancode.SDL_SCANCODE_S,
        T = SDL_Scancode.SDL_SCANCODE_T,
        U = SDL_Scancode.SDL_SCANCODE_U,
        V = SDL_Scancode.SDL_SCANCODE_V,
        W = SDL_Scancode.SDL_SCANCODE_W,
        X = SDL_Scancode.SDL_SCANCODE_X,
        Y = SDL_Scancode.SDL_SCANCODE_Y,
        Z = SDL_Scancode.SDL_SCANCODE_Z,

        Num1 = SDL_Scancode.SDL_SCANCODE_1,
        Num2 = SDL_Scancode.SDL_SCANCODE_2,
        Num3 = SDL_Scancode.SDL_SCANCODE_3,
        Num4 = SDL_Scancode.SDL_SCANCODE_4,
        Num5 = SDL_Scancode.SDL_SCANCODE_5,
        Num6 = SDL_Scancode.SDL_SCANCODE_6,
        Num7 = SDL_Scancode.SDL_SCANCODE_7,
        Num8 = SDL_Scancode.SDL_SCANCODE_8,
        Num9 = SDL_Scancode.SDL_SCANCODE_9,
        Num0 = SDL_Scancode.SDL_SCANCODE_0,

        Return = SDL_Scancode.SDL_SCANCODE_RETURN,
        Escape = SDL_Scancode.SDL_SCANCODE_ESCAPE,
        Backspace = SDL_Scancode.SDL_SCANCODE_BACKSPACE,
        Tab = SDL_Scancode.SDL_SCANCODE_TAB,
        Space = SDL_Scancode.SDL_SCANCODE_SPACE,

        Minus = SDL_Scancode.SDL_SCANCODE_MINUS,
        Equals = SDL_Scancode.SDL_SCANCODE_EQUALS,
        LeftBracket = SDL_Scancode.SDL_SCANCODE_LEFTBRACKET,
        RightBracket = SDL_Scancode.SDL_SCANCODE_RIGHTBRACKET,
        Backslash = SDL_Scancode.SDL_SCANCODE_BACKSLASH,
        NonUsHash = SDL_Scancode.SDL_SCANCODE_NONUSHASH,
        Semicolon = SDL_Scancode.SDL_SCANCODE_SEMICOLON,
        Apostrophe = SDL_Scancode.SDL_SCANCODE_APOSTROPHE,
        Grave = SDL_Scancode.SDL_SCANCODE_GRAVE,
        Comma = SDL_Scancode.SDL_SCANCODE_COMMA,
        Period = SDL_Scancode.SDL_SCANCODE_PERIOD,
        Slash = SDL_Scancode.SDL_SCANCODE_SLASH,
        CapsLock = SDL_Scancode.SDL_SCANCODE_CAPSLOCK,

        F1 = SDL_Scancode.SDL_SCANCODE_F1,
        F2 = SDL_Scancode.SDL_SCANCODE_F2,
        F3 = SDL_Scancode.SDL_SCANCODE_F3,
        F4 = SDL_Scancode.SDL_SCANCODE_F4,
        F5 = SDL_Scancode.SDL_SCANCODE_F5,
        F6 = SDL_Scancode.SDL_SCANCODE_F6,
        F7 = SDL_Scancode.SDL_SCANCODE_F7,
        F8 = SDL_Scancode.SDL_SCANCODE_F8,
        F9 = SDL_Scancode.SDL_SCANCODE_F9,
        F10 = SDL_Scancode.SDL_SCANCODE_F10,
        F11 = SDL_Scancode.SDL_SCANCODE_F11,
        F12 = SDL_Scancode.SDL_SCANCODE_F12,

        PrintScreen = SDL_Scancode.SDL_SCANCODE_PRINTSCREEN,
        ScrollLock = SDL_Scancode.SDL_SCANCODE_SCROLLLOCK,
        Pause = SDL_Scancode.SDL_SCANCODE_PAUSE,
        Insert = SDL_Scancode.SDL_SCANCODE_INSERT,
        Home = SDL_Scancode.SDL_SCANCODE_HOME,
        PageUp = SDL_Scancode.SDL_SCANCODE_PAGEUP,
        Delete = SDL_Scancode.SDL_SCANCODE_DELETE,
        End = SDL_Scancode.SDL_SCANCODE_END,
        PageDown = SDL_Scancode.SDL_SCANCODE_PAGEDOWN,
        Right = SDL_Scancode.SDL_SCANCODE_RIGHT,
        Left = SDL_Scancode.SDL_SCANCODE_LEFT,
        Down = SDL_Scancode.SDL_SCANCODE_DOWN,
        Up = SDL_Scancode.SDL_SCANCODE_UP,

        NumLockClear = SDL_Scancode.SDL_SCANCODE_NUMLOCKCLEAR,
        KpDivide = SDL_Scancode.SDL_SCANCODE_KP_DIVIDE,
        KpMultiply = SDL_Scancode.SDL_SCANCODE_KP_MULTIPLY,
        KpMinus = SDL_Scancode.SDL_SCANCODE_KP_MINUS,
        KpPlus = SDL_Scancode.SDL_SCANCODE_KP_PLUS,
        KpEnter = SDL_Scancode.SDL_SCANCODE_KP_ENTER,
        Kp1 = SDL_Scancode.SDL_SCANCODE_KP_1,
        Kp2 = SDL_Scancode.SDL_SCANCODE_KP_2,
        Kp3 = SDL_Scancode.SDL_SCANCODE_KP_3,
        Kp4 = SDL_Scancode.SDL_SCANCODE_KP_4,
        Kp5 = SDL_Scancode.SDL_SCANCODE_KP_5,
        Kp6 = SDL_Scancode.SDL_SCANCODE_KP_6,
        Kp7 = SDL_Scancode.SDL_SCANCODE_KP_7,
        Kp8 = SDL_Scancode.SDL_SCANCODE_KP_8,
        Kp9 = SDL_Scancode.SDL_SCANCODE_KP_9,
        Kp0 = SDL_Scancode.SDL_SCANCODE_KP_0,
        KpPeriod = SDL_Scancode.SDL_SCANCODE_KP_PERIOD,

        NonUsBackslash = SDL_Scancode.SDL_SCANCODE_NONUSBACKSLASH,
        Application = SDL_Scancode.SDL_SCANCODE_APPLICATION,
        Power = SDL_Scancode.SDL_SCANCODE_POWER,
        KpEquals = SDL_Scancode.SDL_SCANCODE_KP_EQUALS,
        F13 = SDL_Scancode.SDL_SCANCODE_F13,
        F14 = SDL_Scancode.SDL_SCANCODE_F14,
        F15 = SDL_Scancode.SDL_SCANCODE_F15,
        F16 = SDL_Scancode.SDL_SCANCODE_F16,
        F17 = SDL_Scancode.SDL_SCANCODE_F17,
        F18 = SDL_Scancode.SDL_SCANCODE_F18,
        F19 = SDL_Scancode.SDL_SCANCODE_F19,
        F20 = SDL_Scancode.SDL_SCANCODE_F20,
        F21 = SDL_Scancode.SDL_SCANCODE_F21,
        F22 = SDL_Scancode.SDL_SCANCODE_F22,
        F23 = SDL_Scancode.SDL_SCANCODE_F23,
        F24 = SDL_Scancode.SDL_SCANCODE_F24,
        Execute = SDL_Scancode.SDL_SCANCODE_EXECUTE,
        Help = SDL_Scancode.SDL_SCANCODE_HELP,
        Menu = SDL_Scancode.SDL_SCANCODE_MENU,
        Select = SDL_Scancode.SDL_SCANCODE_SELECT,
        Stop = SDL_Scancode.SDL_SCANCODE_STOP,
        Again = SDL_Scancode.SDL_SCANCODE_AGAIN,
        Undo = SDL_Scancode.SDL_SCANCODE_UNDO,
        Cut = SDL_Scancode.SDL_SCANCODE_CUT,
        Copy = SDL_Scancode.SDL_SCANCODE_COPY,
        Paste = SDL_Scancode.SDL_SCANCODE_PASTE,
        Find = SDL_Scancode.SDL_SCANCODE_FIND,
        Mute = SDL_Scancode.SDL_SCANCODE_MUTE,
        VolumeUp = SDL_Scancode.SDL_SCANCODE_VOLUMEUP,
        VolumeDown = SDL_Scancode.SDL_SCANCODE_VOLUMEDOWN,
        KpComma = SDL_Scancode.SDL_SCANCODE_KP_COMMA,
        KpEqualsAS400 = SDL_Scancode.SDL_SCANCODE_KP_EQUALSAS400,

        International1 = SDL_Scancode.SDL_SCANCODE_INTERNATIONAL1,
        International2 = SDL_Scancode.SDL_SCANCODE_INTERNATIONAL2,
        International3 = SDL_Scancode.SDL_SCANCODE_INTERNATIONAL3,
        International4 = SDL_Scancode.SDL_SCANCODE_INTERNATIONAL4,
        International5 = SDL_Scancode.SDL_SCANCODE_INTERNATIONAL5,
        International6 = SDL_Scancode.SDL_SCANCODE_INTERNATIONAL6,
        International7 = SDL_Scancode.SDL_SCANCODE_INTERNATIONAL7,
        International8 = SDL_Scancode.SDL_SCANCODE_INTERNATIONAL8,
        International9 = SDL_Scancode.SDL_SCANCODE_INTERNATIONAL9,
        Lang1 = SDL_Scancode.SDL_SCANCODE_LANG1,
        Lang2 = SDL_Scancode.SDL_SCANCODE_LANG2,
        Lang3 = SDL_Scancode.SDL_SCANCODE_LANG3,
        Lang4 = SDL_Scancode.SDL_SCANCODE_LANG4,
        Lang5 = SDL_Scancode.SDL_SCANCODE_LANG5,
        Lang6 = SDL_Scancode.SDL_SCANCODE_LANG6,
        Lang7 = SDL_Scancode.SDL_SCANCODE_LANG7,
        Lang8 = SDL_Scancode.SDL_SCANCODE_LANG8,
        Lang9 = SDL_Scancode.SDL_SCANCODE_LANG9,

        AltErase = SDL_Scancode.SDL_SCANCODE_ALTERASE,
        SysReq = SDL_Scancode.SDL_SCANCODE_SYSREQ,
        Cancel = SDL_Scancode.SDL_SCANCODE_CANCEL,
        Clear = SDL_Scancode.SDL_SCANCODE_CLEAR,
        Prior = SDL_Scancode.SDL_SCANCODE_PRIOR,
        Return2 = SDL_Scancode.SDL_SCANCODE_RETURN2,
        Separator = SDL_Scancode.SDL_SCANCODE_SEPARATOR,
        Out = SDL_Scancode.SDL_SCANCODE_OUT,
        Oper = SDL_Scancode.SDL_SCANCODE_OPER,
        ClearAgain = SDL_Scancode.SDL_SCANCODE_CLEARAGAIN,
        CrSel = SDL_Scancode.SDL_SCANCODE_CRSEL,
        ExSel = SDL_Scancode.SDL_SCANCODE_EXSEL,

        Kp00 = SDL_Scancode.SDL_SCANCODE_KP_00,
        Kp000 = SDL_Scancode.SDL_SCANCODE_KP_000,
        ThousandsSeparator = SDL_Scancode.SDL_SCANCODE_THOUSANDSSEPARATOR,
        DecimalSeparator = SDL_Scancode.SDL_SCANCODE_DECIMALSEPARATOR,
        CurrencyUnit = SDL_Scancode.SDL_SCANCODE_CURRENCYUNIT,
        CurrencySubUnit = SDL_Scancode.SDL_SCANCODE_CURRENCYSUBUNIT,
        KpLeftParen = SDL_Scancode.SDL_SCANCODE_KP_LEFTPAREN,
        KpRightParen = SDL_Scancode.SDL_SCANCODE_KP_RIGHTPAREN,
        KpLeftBrace = SDL_Scancode.SDL_SCANCODE_KP_LEFTBRACE,
        KpRightBrace = SDL_Scancode.SDL_SCANCODE_KP_RIGHTBRACE,
        KpTab = SDL_Scancode.SDL_SCANCODE_KP_TAB,
        KpBackspace = SDL_Scancode.SDL_SCANCODE_KP_BACKSPACE,
        KpA = SDL_Scancode.SDL_SCANCODE_KP_A,
        KpB = SDL_Scancode.SDL_SCANCODE_KP_B,
        KpC = SDL_Scancode.SDL_SCANCODE_KP_C,
        KpD = SDL_Scancode.SDL_SCANCODE_KP_D,
        KpE = SDL_Scancode.SDL_SCANCODE_KP_E,
        KpF = SDL_Scancode.SDL_SCANCODE_KP_F,
        KpXor = SDL_Scancode.SDL_SCANCODE_KP_XOR,
        KpPower = SDL_Scancode.SDL_SCANCODE_KP_POWER,
        KpPercent = SDL_Scancode.SDL_SCANCODE_KP_PERCENT,
        KpLess = SDL_Scancode.SDL_SCANCODE_KP_LESS,
        KpGreater = SDL_Scancode.SDL_SCANCODE_KP_GREATER,
        KpAmpersand = SDL_Scancode.SDL_SCANCODE_KP_AMPERSAND,
        KpDoubleAmpersand = SDL_Scancode.SDL_SCANCODE_KP_DBLAMPERSAND,
        KpVerticalBar = SDL_Scancode.SDL_SCANCODE_KP_VERTICALBAR,
        KpDoubleVerticalBar = SDL_Scancode.SDL_SCANCODE_KP_DBLVERTICALBAR,
        KpColon = SDL_Scancode.SDL_SCANCODE_KP_COLON,
        KpHash = SDL_Scancode.SDL_SCANCODE_KP_HASH,
        KpSpace = SDL_Scancode.SDL_SCANCODE_KP_SPACE,
        KpAt = SDL_Scancode.SDL_SCANCODE_KP_AT,
        KpExclam = SDL_Scancode.SDL_SCANCODE_KP_EXCLAM,
        KpMemStore = SDL_Scancode.SDL_SCANCODE_KP_MEMSTORE,
        KpMemRecall = SDL_Scancode.SDL_SCANCODE_KP_MEMRECALL,
        KpMemClear = SDL_Scancode.SDL_SCANCODE_KP_MEMCLEAR,
        KpMemAdd = SDL_Scancode.SDL_SCANCODE_KP_MEMADD,
        KpMemSubtract = SDL_Scancode.SDL_SCANCODE_KP_MEMSUBTRACT,
        KpMemMultiply = SDL_Scancode.SDL_SCANCODE_KP_MEMMULTIPLY,
        KpMemDivide = SDL_Scancode.SDL_SCANCODE_KP_MEMDIVIDE,
        KpPlusMinus = SDL_Scancode.SDL_SCANCODE_KP_PLUSMINUS,
        KpClear = SDL_Scancode.SDL_SCANCODE_KP_CLEAR,
        KpClearEntry = SDL_Scancode.SDL_SCANCODE_KP_CLEARENTRY,
        KpBinary = SDL_Scancode.SDL_SCANCODE_KP_BINARY,
        KpOctal = SDL_Scancode.SDL_SCANCODE_KP_OCTAL,
        KpDecimal = SDL_Scancode.SDL_SCANCODE_KP_DECIMAL,
        KpHexadecimal = SDL_Scancode.SDL_SCANCODE_KP_HEXADECIMAL,

        LeftCtrl = SDL_Scancode.SDL_SCANCODE_LCTRL,
        LeftShift = SDL_Scancode.SDL_SCANCODE_LSHIFT,
        LeftAlt = SDL_Scancode.SDL_SCANCODE_LALT,
        LeftGui = SDL_Scancode.SDL_SCANCODE_LGUI,
        RightCtrl = SDL_Scancode.SDL_SCANCODE_RCTRL,
        RightShift = SDL_Scancode.SDL_SCANCODE_RSHIFT,
        RightAlt = SDL_Scancode.SDL_SCANCODE_RALT,
        RightGui = SDL_Scancode.SDL_SCANCODE_RGUI,

        Mode = SDL_Scancode.SDL_SCANCODE_MODE,

        Sleep = SDL_Scancode.SDL_SCANCODE_SLEEP,
        Wake = SDL_Scancode.SDL_SCANCODE_WAKE,

        ChannelIncrement = SDL_Scancode.SDL_SCANCODE_CHANNEL_INCREMENT,
        ChannelDecrement = SDL_Scancode.SDL_SCANCODE_CHANNEL_DECREMENT,

        MediaPlay = SDL_Scancode.SDL_SCANCODE_MEDIA_PLAY,
        MediaPause = SDL_Scancode.SDL_SCANCODE_MEDIA_PAUSE,
        MediaRecord = SDL_Scancode.SDL_SCANCODE_MEDIA_RECORD,
        MediaFastForward = SDL_Scancode.SDL_SCANCODE_MEDIA_FAST_FORWARD,
        MediaRewind = SDL_Scancode.SDL_SCANCODE_MEDIA_REWIND,
        MediaNextTrack = SDL_Scancode.SDL_SCANCODE_MEDIA_NEXT_TRACK,
        MediaPreviousTrack = SDL_Scancode.SDL_SCANCODE_MEDIA_PREVIOUS_TRACK,
        MediaStop = SDL_Scancode.SDL_SCANCODE_MEDIA_STOP,
        MediaEject = SDL_Scancode.SDL_SCANCODE_MEDIA_EJECT,
        MediaPlayPause = SDL_Scancode.SDL_SCANCODE_MEDIA_PLAY_PAUSE,
        MediaSelect = SDL_Scancode.SDL_SCANCODE_MEDIA_SELECT,

        AcNew = SDL_Scancode.SDL_SCANCODE_AC_NEW,
        AcOpen = SDL_Scancode.SDL_SCANCODE_AC_OPEN,
        AcClose = SDL_Scancode.SDL_SCANCODE_AC_CLOSE,
        AcExit = SDL_Scancode.SDL_SCANCODE_AC_EXIT,
        AcSave = SDL_Scancode.SDL_SCANCODE_AC_SAVE,
        AcPrint = SDL_Scancode.SDL_SCANCODE_AC_PRINT,
        AcProperties = SDL_Scancode.SDL_SCANCODE_AC_PROPERTIES,

        AcSearch = SDL_Scancode.SDL_SCANCODE_AC_SEARCH,
        AcHome = SDL_Scancode.SDL_SCANCODE_AC_HOME,
        AcBack = SDL_Scancode.SDL_SCANCODE_AC_BACK,
        AcForward = SDL_Scancode.SDL_SCANCODE_AC_FORWARD,
        AcStop = SDL_Scancode.SDL_SCANCODE_AC_STOP,
        AcRefresh = SDL_Scancode.SDL_SCANCODE_AC_REFRESH,
        AcBookmarks = SDL_Scancode.SDL_SCANCODE_AC_BOOKMARKS,

        SoftLeft = SDL_Scancode.SDL_SCANCODE_SOFTLEFT,
        SoftRight = SDL_Scancode.SDL_SCANCODE_SOFTRIGHT,
        Call = SDL_Scancode.SDL_SCANCODE_CALL,
        EndCall = SDL_Scancode.SDL_SCANCODE_ENDCALL,

        [EditorBrowsable(EditorBrowsableState.Never)]
        Reserved = SDL_Scancode.SDL_SCANCODE_RESERVED,

        [EditorBrowsable(EditorBrowsableState.Never)]
        Count = SDL_Scancode.SDL_SCANCODE_COUNT
    }

    public enum KeySymbol : uint
    {
        Unknown = SDL3.SDLK_UNKNOWN,
        Return = SDL3.SDLK_RETURN,
        Escape = SDL3.SDLK_ESCAPE,
        Backspace = SDL3.SDLK_BACKSPACE,
        Tab = SDL3.SDLK_TAB,
        Space = SDL3.SDLK_SPACE,
        Exclaim = SDL3.SDLK_EXCLAIM,
        DblApostrophe = SDL3.SDLK_DBLAPOSTROPHE,
        Hash = SDL3.SDLK_HASH,
        Dollar = SDL3.SDLK_DOLLAR,
        Percent = SDL3.SDLK_PERCENT,
        Ampersand = SDL3.SDLK_AMPERSAND,
        Apostrophe = SDL3.SDLK_APOSTROPHE,
        LeftParen = SDL3.SDLK_LEFTPAREN,
        RightParen = SDL3.SDLK_RIGHTPAREN,
        Asterisk = SDL3.SDLK_ASTERISK,
        Plus = SDL3.SDLK_PLUS,
        Comma = SDL3.SDLK_COMMA,
        Minus = SDL3.SDLK_MINUS,
        Period = SDL3.SDLK_PERIOD,
        Slash = SDL3.SDLK_SLASH,
        D0 = SDL3.SDLK_0,
        D1 = SDL3.SDLK_1,
        D2 = SDL3.SDLK_2,
        D3 = SDL3.SDLK_3,
        D4 = SDL3.SDLK_4,
        D5 = SDL3.SDLK_5,
        D6 = SDL3.SDLK_6,
        D7 = SDL3.SDLK_7,
        D8 = SDL3.SDLK_8,
        D9 = SDL3.SDLK_9,
        Colon = SDL3.SDLK_COLON,
        Semicolon = SDL3.SDLK_SEMICOLON,
        Less = SDL3.SDLK_LESS,
        Equals = SDL3.SDLK_EQUALS,
        Greater = SDL3.SDLK_GREATER,
        Question = SDL3.SDLK_QUESTION,
        At = SDL3.SDLK_AT,
        LeftBracket = SDL3.SDLK_LEFTBRACKET,
        Backslash = SDL3.SDLK_BACKSLASH,
        RightBracket = SDL3.SDLK_RIGHTBRACKET,
        Caret = SDL3.SDLK_CARET,
        Underscore = SDL3.SDLK_UNDERSCORE,
        Grave = SDL3.SDLK_GRAVE,
        A = SDL3.SDLK_A,
        B = SDL3.SDLK_B,
        C = SDL3.SDLK_C,
        D = SDL3.SDLK_D,
        E = SDL3.SDLK_E,
        F = SDL3.SDLK_F,
        G = SDL3.SDLK_G,
        H = SDL3.SDLK_H,
        I = SDL3.SDLK_I,
        J = SDL3.SDLK_J,
        K = SDL3.SDLK_K,
        L = SDL3.SDLK_L,
        M = SDL3.SDLK_M,
        N = SDL3.SDLK_N,
        O = SDL3.SDLK_O,
        P = SDL3.SDLK_P,
        Q = SDL3.SDLK_Q,
        R = SDL3.SDLK_R,
        S = SDL3.SDLK_S,
        T = SDL3.SDLK_T,
        U = SDL3.SDLK_U,
        V = SDL3.SDLK_V,
        W = SDL3.SDLK_W,
        X = SDL3.SDLK_X,
        Y = SDL3.SDLK_Y,
        Z = SDL3.SDLK_Z,
        LeftBrace = SDL3.SDLK_LEFTBRACE,
        Pipe = SDL3.SDLK_PIPE,
        RightBrace = SDL3.SDLK_RIGHTBRACE,
        Tilde = SDL3.SDLK_TILDE,
        Delete = SDL3.SDLK_DELETE,
        PlusMinus = SDL3.SDLK_PLUSMINUS,
        CapsLock = SDL3.SDLK_CAPSLOCK,
        F1 = SDL3.SDLK_F1,
        F2 = SDL3.SDLK_F2,
        F3 = SDL3.SDLK_F3,
        F4 = SDL3.SDLK_F4,
        F5 = SDL3.SDLK_F5,
        F6 = SDL3.SDLK_F6,
        F7 = SDL3.SDLK_F7,
        F8 = SDL3.SDLK_F8,
        F9 = SDL3.SDLK_F9,
        F10 = SDL3.SDLK_F10,
        F11 = SDL3.SDLK_F11,
        F12 = SDL3.SDLK_F12,
        PrintScreen = SDL3.SDLK_PRINTSCREEN,
        ScrollLock = SDL3.SDLK_SCROLLLOCK,
        Pause = SDL3.SDLK_PAUSE,
        Insert = SDL3.SDLK_INSERT,
        Home = SDL3.SDLK_HOME,
        PageUp = SDL3.SDLK_PAGEUP,
        End = SDL3.SDLK_END,
        PageDown = SDL3.SDLK_PAGEDOWN,
        Right = SDL3.SDLK_RIGHT,
        Left = SDL3.SDLK_LEFT,
        Down = SDL3.SDLK_DOWN,
        Up = SDL3.SDLK_UP,
        NumLockClear = SDL3.SDLK_NUMLOCKCLEAR,
        KpDivide = SDL3.SDLK_KP_DIVIDE,
        KpMultiply = SDL3.SDLK_KP_MULTIPLY,
        KpMinus = SDL3.SDLK_KP_MINUS,
        KpPlus = SDL3.SDLK_KP_PLUS,
        KpEnter = SDL3.SDLK_KP_ENTER,
        Kp1 = SDL3.SDLK_KP_1,
        Kp2 = SDL3.SDLK_KP_2,
        Kp3 = SDL3.SDLK_KP_3,
        Kp4 = SDL3.SDLK_KP_4,
        Kp5 = SDL3.SDLK_KP_5,
        Kp6 = SDL3.SDLK_KP_6,
        Kp7 = SDL3.SDLK_KP_7,
        Kp8 = SDL3.SDLK_KP_8,
        Kp9 = SDL3.SDLK_KP_9,
        Kp0 = SDL3.SDLK_KP_0,
        KpPeriod = SDL3.SDLK_KP_PERIOD,
        Application = SDL3.SDLK_APPLICATION,
        Power = SDL3.SDLK_POWER,
        KpEquals = SDL3.SDLK_KP_EQUALS,
        F13 = SDL3.SDLK_F13,
        F14 = SDL3.SDLK_F14,
        F15 = SDL3.SDLK_F15,
        F16 = SDL3.SDLK_F16,
        F17 = SDL3.SDLK_F17,
        F18 = SDL3.SDLK_F18,
        F19 = SDL3.SDLK_F19,
        F20 = SDL3.SDLK_F20,
        F21 = SDL3.SDLK_F21,
        F22 = SDL3.SDLK_F22,
        F23 = SDL3.SDLK_F23,
        F24 = SDL3.SDLK_F24,
        Execute = SDL3.SDLK_EXECUTE,
        Help = SDL3.SDLK_HELP,
        Menu = SDL3.SDLK_MENU,
        Select = SDL3.SDLK_SELECT,
        Stop = SDL3.SDLK_STOP,
        Again = SDL3.SDLK_AGAIN,
        Undo = SDL3.SDLK_UNDO,
        Cut = SDL3.SDLK_CUT,
        Copy = SDL3.SDLK_COPY,
        Paste = SDL3.SDLK_PASTE,
        Find = SDL3.SDLK_FIND,
        Mute = SDL3.SDLK_MUTE,
        VolumeUp = SDL3.SDLK_VOLUMEUP,
        VolumeDown = SDL3.SDLK_VOLUMEDOWN,
        KpComma = SDL3.SDLK_KP_COMMA,
        KpEqualsAs400 = SDL3.SDLK_KP_EQUALSAS400,
        Alterase = SDL3.SDLK_ALTERASE,
        SysReq = SDL3.SDLK_SYSREQ,
        Cancel = SDL3.SDLK_CANCEL,
        Clear = SDL3.SDLK_CLEAR,
        Prior = SDL3.SDLK_PRIOR,
        Return2 = SDL3.SDLK_RETURN2,
        Separator = SDL3.SDLK_SEPARATOR,
        Out = SDL3.SDLK_OUT,
        Oper = SDL3.SDLK_OPER,
        ClearAgain = SDL3.SDLK_CLEARAGAIN,
        CrSel = SDL3.SDLK_CRSEL,
        ExSel = SDL3.SDLK_EXSEL,
        Kp00 = SDL3.SDLK_KP_00,
        Kp000 = SDL3.SDLK_KP_000,
        ThousandsSeparator = SDL3.SDLK_THOUSANDSSEPARATOR,
        DecimalSeparator = SDL3.SDLK_DECIMALSEPARATOR,
        CurrencyUnit = SDL3.SDLK_CURRENCYUNIT,
        CurrencySubunit = SDL3.SDLK_CURRENCYSUBUNIT,
        KpLeftParen = SDL3.SDLK_KP_LEFTPAREN,
        KpRightParen = SDL3.SDLK_KP_RIGHTPAREN,
        KpLeftBrace = SDL3.SDLK_KP_LEFTBRACE,
        KpRightBrace = SDL3.SDLK_KP_RIGHTBRACE,
        KpTab = SDL3.SDLK_KP_TAB,
        KpBackspace = SDL3.SDLK_KP_BACKSPACE,
        KpA = SDL3.SDLK_KP_A,
        KpB = SDL3.SDLK_KP_B,
        KpC = SDL3.SDLK_KP_C,
        KpD = SDL3.SDLK_KP_D,
        KpE = SDL3.SDLK_KP_E,
        KpF = SDL3.SDLK_KP_F,
        KpXor = SDL3.SDLK_KP_XOR,
        KpPower = SDL3.SDLK_KP_POWER,
        KpPercent = SDL3.SDLK_KP_PERCENT,
        KpLess = SDL3.SDLK_KP_LESS,
        KpGreater = SDL3.SDLK_KP_GREATER,
        KpAmpersand = SDL3.SDLK_KP_AMPERSAND,
        KpDblAmpersand = SDL3.SDLK_KP_DBLAMPERSAND,
        KpVerticalBar = SDL3.SDLK_KP_VERTICALBAR,
        KpDblVerticalBar = SDL3.SDLK_KP_DBLVERTICALBAR,
        KpColon = SDL3.SDLK_KP_COLON,
        KpHash = SDL3.SDLK_KP_HASH,
        KpSpace = SDL3.SDLK_KP_SPACE,
        KpAt = SDL3.SDLK_KP_AT,
        KpExclam = SDL3.SDLK_KP_EXCLAM,
        KpMemStore = SDL3.SDLK_KP_MEMSTORE,
        KpMemRecall = SDL3.SDLK_KP_MEMRECALL,
        KpMemClear = SDL3.SDLK_KP_MEMCLEAR,
        KpMemAdd = SDL3.SDLK_KP_MEMADD,
        KpMemSubtract = SDL3.SDLK_KP_MEMSUBTRACT,
        KpMemMultiply = SDL3.SDLK_KP_MEMMULTIPLY,
        KpMemDivide = SDL3.SDLK_KP_MEMDIVIDE,
        KpPlusMinus = SDL3.SDLK_KP_PLUSMINUS,
        KpClear = SDL3.SDLK_KP_CLEAR,
        KpClearEntry = SDL3.SDLK_KP_CLEARENTRY,
        KpBinary = SDL3.SDLK_KP_BINARY,
        KpOctal = SDL3.SDLK_KP_OCTAL,
        KpDecimal = SDL3.SDLK_KP_DECIMAL,
        KpHexadecimal = SDL3.SDLK_KP_HEXADECIMAL,
        LCtrl = SDL3.SDLK_LCTRL,
        LShift = SDL3.SDLK_LSHIFT,
        LAlt = SDL3.SDLK_LALT,
        LGui = SDL3.SDLK_LGUI,
        RCtrl = SDL3.SDLK_RCTRL,
        RShift = SDL3.SDLK_RSHIFT,
        RAlt = SDL3.SDLK_RALT,
        RGui = SDL3.SDLK_RGUI,
        Mode = SDL3.SDLK_MODE,
        Sleep = SDL3.SDLK_SLEEP,
        Wake = SDL3.SDLK_WAKE,
        ChannelIncrement = SDL3.SDLK_CHANNEL_INCREMENT,
        ChannelDecrement = SDL3.SDLK_CHANNEL_DECREMENT,
        MediaPlay = SDL3.SDLK_MEDIA_PLAY,
        MediaPause = SDL3.SDLK_MEDIA_PAUSE,
        MediaRecord = SDL3.SDLK_MEDIA_RECORD,
        MediaFastForward = SDL3.SDLK_MEDIA_FAST_FORWARD,
        MediaRewind = SDL3.SDLK_MEDIA_REWIND,
        MediaNextTrack = SDL3.SDLK_MEDIA_NEXT_TRACK,
        MediaPreviousTrack = SDL3.SDLK_MEDIA_PREVIOUS_TRACK,
        MediaStop = SDL3.SDLK_MEDIA_STOP,
        MediaEject = SDL3.SDLK_MEDIA_EJECT,
        MediaPlayPause = SDL3.SDLK_MEDIA_PLAY_PAUSE,
        MediaSelect = SDL3.SDLK_MEDIA_SELECT,
        AcNew = SDL3.SDLK_AC_NEW,
        AcOpen = SDL3.SDLK_AC_OPEN,
        AcClose = SDL3.SDLK_AC_CLOSE,
        AcExit = SDL3.SDLK_AC_EXIT,
        AcSave = SDL3.SDLK_AC_SAVE,
        AcPrint = SDL3.SDLK_AC_PRINT,
        AcProperties = SDL3.SDLK_AC_PROPERTIES,
        AcSearch = SDL3.SDLK_AC_SEARCH,
        AcHome = SDL3.SDLK_AC_HOME,
        AcBack = SDL3.SDLK_AC_BACK,
        AcForward = SDL3.SDLK_AC_FORWARD,
        AcStop = SDL3.SDLK_AC_STOP,
        AcRefresh = SDL3.SDLK_AC_REFRESH,
        AcBookmarks = SDL3.SDLK_AC_BOOKMARKS,
        SoftLeft = SDL3.SDLK_SOFTLEFT,
        SoftRight = SDL3.SDLK_SOFTRIGHT,
        Call = SDL3.SDLK_CALL,
        EndCall = SDL3.SDLK_ENDCALL,
        LeftTab = SDL3.SDLK_LEFT_TAB,
        Level5Shift = SDL3.SDLK_LEVEL5_SHIFT,
        MultiKeyCompose = SDL3.SDLK_MULTI_KEY_COMPOSE,
        LMeta = SDL3.SDLK_LMETA,
        RMeta = SDL3.SDLK_RMETA,
        LHyper = SDL3.SDLK_LHYPER,
        RHyper = SDL3.SDLK_RHYPER,
    }
}
